// import all controllers
import './modules/user/user.controller'
import './modules/auth/auth.controller'
import './modules/degree/degree.controller'
import './modules/department/department.controller'
import './modules/course/course.controller'
import './modules/student/student.controller'
import './modules/professor/professor.controller'
import './modules/educationAssistant/educationAssistant.controller'
import './modules/universityPresident/universityPresident.controller'
import './modules/semester/semester.controller'
import './modules/class/class.controller'
import './modules/classProfessor/classProfessor.controller'
import './modules/classSchedule/ClassSchedule.controller'
import './modules/importantDate/importantDate.controller'
